### PR TITLE
Use electron-packager to create an os x bundle

### PR DESCRIPTION
**Pull request by portellaa**
Hi, so first of all, congratulations for the work, it's really great app.

So, i usually like to have the applications as a bundle or brew formula (cask included), so this is just a pull request to allow the creation of os x bundle using electron packager.

This changes the `.gitignore` to include the `bin` folder and the `package.json` with the `electron-packager` dependency and an extra script.

### CODE REVIEW

**Comment by portellaa** [comment]
You just need to run `npm run build` to generate the package

**Comment by samccone** [comment]
oh this is a nice idea... @portellaa what would you think about adding this to the readme?

**Comment by portellaa** [comment]
Yes of course. Just checking if you guys like and supports the idea.
I'll change in a bit and commit it :wink:

**Comment by RangerMauve** [comment]
Any chance of adding linux/windows to be package-able from this pr as well?

**Comment by portellaa** [comment]
@RangerMauve yes. have you confirmed that this is running out-of-box on those platforms? That is the only reason that i don't add this support.

**Comment by RangerMauve** [comment]
@portellaa I haven't tried it yet, actually. But the README did mention how to set it up on linux/windows so I assumed that they had it working. Could @kdzwinel confirm this? :o

**Comment by c0b41** [comment]
@portellaa @RangerMauve i think very cool boilerplate, and linux windows mac build tool https://github.com/szwacz/electron-boilerplate

**Comment by portellaa** [comment]
@ayhankuru can you explain why we need the boilerplate? the application is made and working. just asking :smile: 

@RangerMauve yes, it seems this works. have created the package and tried. I will commit to the package.json.

**Comment by c0b41** [comment]
@portellaa not need boilerplate, https://github.com/szwacz/electron-boilerplate/tree/master/tasks
need linux deb or windows exe file something..

**Comment by portellaa** [comment]
@RangerMauve added scripts for linux and windows. I also changed it a little bit so you can run custom builds, for example, if you want a build for windows 64 bits only you can use `npm run build:custom -- --platform=win32 --arch=x64`

@ayhankuru ok, i'll take a deeper look into that. I was thinking on use https://www.npmjs.com/package/electron-builder to build windows and linux packages.
What do you think?

@samccone README update will come out in a while, sorry.

So the scripts to create packages are now:
- `npm run build` -> creates binaries to all the systems and platforms
- `npm run build:linux` -> creates linux binaries
- `npm run build:osx` -> creates osx binaries, 64 bits only
- `npm run build:win` -> creates windows binaries
- `npm run build:custom` -> configurable one that allows to specify `platform` and `arch` input arguments. example: `npm run build:custom -- --platform=osx --arch=ia32`

**Comment by samccone** [comment]
awesome work @portellaa :) thanks for this work :+1:

**Comment by c0b41** [comment]
@portellaa cool, good available..  but linux :)

**Comment by kdzwinel** [comment]
@portellaa awesome work! It's my first electron app, so your knowledge in this area is very much appreciated. Let's add README update that Sam mentioned and merge that thing!

BTW should I put these packages under /release or just expect everyone to create them locally?

**Comment by portellaa** [comment]
@kdzwinel thanks, my knowledge it's not so much as this, i only create a small package when atom came out with this.
When electron came out, i get curious because i saw a lot of applications that seems to me that they are nodeJS, like slack, so i made a few searches on that.

Yes, i think you should create a release with that included, but not push them to the master i think it's "garbage" to the repo, but that is just my idea of course :wink: 

About @ayhankuru changes, do you think that should be a different PR? i think we should create a windows installer and linux packages to be easier to install :smiley:

**Comment by portellaa** [comment]
@samccone @kdzwinel check the README and let me know what to improve :) All the comments are welcome @RangerMauve @ayhankuru

**Comment by kdzwinel** [comment]
### Releases

@portellaa yeah, I was thinking about keeping builds under `/releases` (similarly to what [atom does](https://github.com/atom/atom/releases) ).

### Boilerplate

@portellaa @ayhankuru  I still don't quite understand why we need that boilerplate?

### Readme

Good work! However, since we decided to keep builds under `/releases` I'd encourage people to simply download them (instead of building). We should keep information about building in the wiki though. WDYT?

**Comment by portellaa** [comment]
*\* Releases **
@kdzwinel U'r talking about the releases tab on GH, right? I think it's the same as `/releases`.

*\* Boilerplate **
@kdzwinel what @ayhankuru want to say, is to create packages do some linux distributions, such as debian based, rpm based, you know? Lets leave this to another PR, ok? Will discuss that there.

*\* Readme **
I think we should have both approaches there, no? Having the _Installing_ section and the _Building_ section.
WDYT?

Let me know as soon WDYT so i can update the README :wink:

**Comment by kdzwinel** [comment]
@portellaa having separate sections for installing and bundling makes sense - let's do that! I'll generate and put all the bundles in releases tab as soon as we merge.

**Comment by c0b41** [comment]
@portellaa @kdzwinel not need, merge this :+1:

**Comment by portellaa** [comment]
@kdzwinel check the README. Sorry by the delay, i was travelling :)

**Comment by kdzwinel** [comment]
@portellaa thanks for your work! I'll merge that tomorrow - I have to create and test bundles first.

**Comment by portellaa** [comment]
@kdzwinel you're welcome, but i'm the one that congratulates you for the application, it's really great.
I only tested the os x bundle and it works out of box :wink:

**Comment by c0b41** [comment]
@portellaa thanks, so cool :+1: 
Betwixt

**Comment by portellaa** [comment]
Betwixt working on Mac OS X El Capitan 10.11.2 Beta :smiley: 
screen shot 2015-12-02 at 00 05 05

**Pull request merged**
